import type { DropApiDrop, DropProduct, WorkflowSignoff, WorkflowStage } from "@/types/drops";

// Satisfy TS while keeping mock-data readable
type Signoffs = Partial<Record<WorkflowStage, WorkflowSignoff>>;
const NO_SIGNOFFS: Signoffs = {};

export const MOCK_DROPS: DropApiDrop[] = [
  {
    tag: "5.1.26",
    date: "2026-05-01T00:00:00.000Z",
    type: "bags",
    name: "May Drop 1 — Bags",
    productCount: 18,
    activeCount: 18,
    status: "ended",
    channels: ["shopify", "tiktok"],
    completionPct: 100,
    signoffs: NO_SIGNOFFS,
  },
  {
    tag: "5.8.26",
    date: "2026-05-08T00:00:00.000Z",
    type: "watches",
    name: "May Drop 2 — Watches",
    productCount: 12,
    activeCount: 12,
    status: "ended",
    channels: ["shopify"],
    completionPct: 100,
    signoffs: NO_SIGNOFFS,
  },
  {
    tag: "5.15.26",
    date: "2026-05-15T00:00:00.000Z",
    type: "mixed",
    name: "May Drop 3",
    productCount: 28,
    activeCount: 28,
    status: "upcoming",
    channels: ["shopify", "tiktok", "whatnot"],
    completionPct: 68,
    signoffs: NO_SIGNOFFS,
  },
  {
    tag: "5.22.26",
    date: "2026-05-22T00:00:00.000Z",
    type: "bags",
    name: "May Drop 4 — Bags",
    productCount: 15,
    activeCount: 15,
    status: "draft",
    channels: ["shopify"],
    completionPct: 20,
    signoffs: NO_SIGNOFFS,
  },
  {
    tag: "5.29.26",
    date: "2026-05-29T00:00:00.000Z",
    type: "mixed",
    name: "May Drop 5",
    productCount: 0,
    activeCount: 0,
    status: "future",
    channels: ["shopify"],
    completionPct: 0,
    signoffs: NO_SIGNOFFS,
  },
];

export const MOCK_PRODUCTS: DropProduct[] = [
  {
    id: "gid://shopify/Product/1",
    title: "Louis Vuitton Neverfull MM Monogram",
    description: "Classic monogram canvas tote in excellent pre-owned condition. All hardware intact, minor patina on handles.",
    handle: "lv-neverfull-mm",
    status: "ACTIVE",
    tags: ["5.15.26", "bags"],
    sku: "LV-NF-001",
    variantId: "gid://shopify/ProductVariant/1",
    images: [
      {
        id: "1",
        url: "https://placehold.co/96x96/f2ede9/8a7a72?text=LV",
        altText: "Louis Vuitton Neverfull",
      },
      {
        id: "2",
        url: "https://placehold.co/96x96/f2ede9/8a7a72?text=LV2",
        altText: "Interior view",
      },
    ],
    price: "0",
    compareAtPrice: null,
    inventoryQuantity: 1,
    cost: "450",
    conditionGrade: null,
    material: "Coated canvas",
    hardwareColor: "Gold",
    year: "2019",
    serialNumber: "SD4189",
    reshootNotes: null,
    tiktokPrice: null,
    whatnotPrice: null,
  },
  {
    id: "gid://shopify/Product/2",
    title: "Chanel Classic Flap Medium Black Caviar",
    description: "",
    handle: "chanel-cf-medium",
    status: "ACTIVE",
    tags: ["5.15.26", "bags", "needs-reshoot"],
    sku: "CC-CF-002",
    variantId: "gid://shopify/ProductVariant/2",
    images: [
      {
        id: "3",
        url: "https://placehold.co/96x96/f2ede9/8a7a72?text=CC",
        altText: "Chanel Classic Flap",
      },
      {
        id: "4",
        url: "https://placehold.co/96x96/f2ede9/8a7a72?text=CC2",
        altText: "Back view",
      },
    ],
    price: "0",
    compareAtPrice: null,
    inventoryQuantity: 1,
    cost: "1200",
    conditionGrade: "A",
    material: null,
    hardwareColor: null,
    year: null,
    serialNumber: null,
    reshootNotes: "Need better lighting on clasp",
    tiktokPrice: null,
    whatnotPrice: null,
  },
  {
    id: "gid://shopify/Product/3",
    title: "Gucci Dionysus Small Shoulder Bag",
    description: "Authentic Gucci Dionysus in GG Supreme canvas with suede trim. Tiger head closure hardware in aged gold tone.",
    handle: "gucci-dionysus-small",
    status: "ACTIVE",
    tags: ["5.15.26", "bags", "tiktok-sync"],
    sku: "GU-DS-003",
    variantId: "gid://shopify/ProductVariant/3",
    images: [
      {
        id: "5",
        url: "https://placehold.co/96x96/f2ede9/8a7a72?text=GU",
        altText: "Gucci Dionysus",
      },
      {
        id: "6",
        url: "https://placehold.co/96x96/f2ede9/8a7a72?text=GU2",
        altText: "Side view",
      },
      {
        id: "7",
        url: "https://placehold.co/96x96/f2ede9/8a7a72?text=GU3",
        altText: "Hardware detail",
      },
    ],
    price: "650",
    compareAtPrice: "750",
    inventoryQuantity: 1,
    cost: "380",
    conditionGrade: "B",
    material: "GG Supreme canvas",
    hardwareColor: "Aged gold",
    year: "2021",
    serialNumber: "632702",
    reshootNotes: null,
    tiktokPrice: "620",
    whatnotPrice: null,
  },
  {
    id: "gid://shopify/Product/4",
    title: "Prada Tessuto Nylon Backpack Black",
    description: "",
    handle: "prada-tessuto-backpack",
    status: "ACTIVE",
    tags: ["5.15.26", "bags"],
    sku: "PR-TB-004",
    variantId: "gid://shopify/ProductVariant/4",
    images: [
      {
        id: "8",
        url: "https://placehold.co/96x96/f2ede9/8a7a72?text=PR",
        altText: "Prada Backpack",
      },
    ],
    price: "420",
    compareAtPrice: null,
    inventoryQuantity: 1,
    cost: "200",
    conditionGrade: null,
    material: null,
    hardwareColor: null,
    year: null,
    serialNumber: null,
    reshootNotes: null,
    tiktokPrice: null,
    whatnotPrice: null,
  },
];
